/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTafiRouteImport } from './routes/_authenticated/tafi'
import { Route as TafiSetupRouteImport } from './routes/tafi.setup'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin.drivers'
import { Route as AuthenticatedAdminGuardiansRouteImport } from './routes/_authenticated/admin.guardians'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin.routes'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminVehiclesRouteImport } from './routes/_authenticated/admin.vehicles'
import { Route as AuthenticatedTafiIndexRouteImport } from './routes/_authenticated/tafi.index'
import { Route as AuthenticatedTafiUsersRouteImport } from './routes/_authenticated/tafi.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTafiRoute = AuthenticatedTafiRouteImport.update({
  id: '/tafi',
  path: '/tafi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TafiSetupRoute = TafiSetupRouteImport.update({
  id: '/tafi/setup',
  path: '/tafi/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuardiansRoute =
  AuthenticatedAdminGuardiansRouteImport.update({
    id: '/guardians',
    path: '/guardians',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVehiclesRoute =
  AuthenticatedAdminVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTafiIndexRoute = AuthenticatedTafiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTafiRoute,
} as any)
const AuthenticatedTafiUsersRoute = AuthenticatedTafiUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedTafiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/tafi': typeof AuthenticatedTafiRouteWithChildren
  '/tafi/setup': typeof TafiSetupRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/guardians': typeof AuthenticatedAdminGuardiansRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/tafi/users': typeof AuthenticatedTafiUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tafi/': typeof AuthenticatedTafiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tafi/setup': typeof TafiSetupRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/guardians': typeof AuthenticatedAdminGuardiansRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/tafi/users': typeof AuthenticatedTafiUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tafi': typeof AuthenticatedTafiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/tafi': typeof AuthenticatedTafiRouteWithChildren
  '/tafi/setup': typeof TafiSetupRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/guardians': typeof AuthenticatedAdminGuardiansRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/_authenticated/tafi/users': typeof AuthenticatedTafiUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tafi/': typeof AuthenticatedTafiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/tafi'
    | '/tafi/setup'
    | '/admin/billing'
    | '/admin/drivers'
    | '/admin/guardians'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/vehicles'
    | '/tafi/users'
    | '/admin/'
    | '/tafi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tafi/setup'
    | '/admin/billing'
    | '/admin/drivers'
    | '/admin/guardians'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/vehicles'
    | '/tafi/users'
    | '/admin'
    | '/tafi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/tafi'
    | '/tafi/setup'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/guardians'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/vehicles'
    | '/_authenticated/tafi/users'
    | '/_authenticated/admin/'
    | '/_authenticated/tafi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TafiSetupRoute: typeof TafiSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tafi': {
      id: '/_authenticated/tafi'
      path: '/tafi'
      fullPath: '/tafi'
      preLoaderRoute: typeof AuthenticatedTafiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tafi/setup': {
      id: '/tafi/setup'
      path: '/tafi/setup'
      fullPath: '/tafi/setup'
      preLoaderRoute: typeof TafiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guardians': {
      id: '/_authenticated/admin/guardians'
      path: '/guardians'
      fullPath: '/admin/guardians'
      preLoaderRoute: typeof AuthenticatedAdminGuardiansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vehicles': {
      id: '/_authenticated/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tafi/': {
      id: '/_authenticated/tafi/'
      path: '/'
      fullPath: '/tafi/'
      preLoaderRoute: typeof AuthenticatedTafiIndexRouteImport
      parentRoute: typeof AuthenticatedTafiRoute
    }
    '/_authenticated/tafi/users': {
      id: '/_authenticated/tafi/users'
      path: '/users'
      fullPath: '/tafi/users'
      preLoaderRoute: typeof AuthenticatedTafiUsersRouteImport
      parentRoute: typeof AuthenticatedTafiRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminGuardiansRoute: typeof AuthenticatedAdminGuardiansRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminVehiclesRoute: typeof AuthenticatedAdminVehiclesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
  AuthenticatedAdminGuardiansRoute: AuthenticatedAdminGuardiansRoute,
  AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminVehiclesRoute: AuthenticatedAdminVehiclesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTafiRouteChildren {
  AuthenticatedTafiUsersRoute: typeof AuthenticatedTafiUsersRoute
  AuthenticatedTafiIndexRoute: typeof AuthenticatedTafiIndexRoute
}

const AuthenticatedTafiRouteChildren: AuthenticatedTafiRouteChildren = {
  AuthenticatedTafiUsersRoute: AuthenticatedTafiUsersRoute,
  AuthenticatedTafiIndexRoute: AuthenticatedTafiIndexRoute,
}

const AuthenticatedTafiRouteWithChildren =
  AuthenticatedTafiRoute._addFileChildren(AuthenticatedTafiRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedTafiRoute: typeof AuthenticatedTafiRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedTafiRoute: AuthenticatedTafiRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TafiSetupRoute: TafiSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
